# Generated by Django 2.1.7 on 2019-03-19 20:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190313_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(template='blog/blocks/heading.html')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock(template='blog/blocks/image.html')), ('code', wagtail.core.blocks.StructBlock([('code', wagtail.core.blocks.TextBlock())]))], blank=True, null=True),
        ),
    ]
